### PR TITLE
Removed necessity for meetup_config.php

### PR DESCRIPTION
**Pull request by cjlarose**
I've removed the meetup_config.php file in favor of the construction of MeetupConnection objects.  This means that projects that use this API wrapper can use a dynamic API key (such as in the case that the project accepts an API key from the user).

### CODE REVIEW

**Comment by blobaugh** [comment]
Great idea! I have been wanting to setup a class to handle whatever auth the user chooses, be it API key or oauth but have not had to to circle back for a while. Any ideas on that?

**Comment by cjlarose** [comment]
Yeah I definitely tried to create that MeetupConnection class in a way that might allow both key auth and oAuth.

Whenever oAuth supports comes in, this is how I see it happening:
- There are several classes that extend the MeetupConnection class.  One for key auth and one for oAuth 2 for now.  Let's call them KeyAuthMeetupConnection and OAuth2MeetupConnection
- Each of them implements a get() and a buildurl() method. (The get() and buildurl() methods of ApiRequest should be moved over to the KeyAuthMeetupConnection class).  This is because the different auth methods will use different request parameters and headers and such.
- The ApiRequest class's get() method just calls get() of it's private $_conn attribute, which is an instance of either KeyAuth MeetupConnection or OAuth2MeetupConnection

Users would just do something like this:

``` php
$conn = KeyAuthMeetupConnection('abc123mykey');
$e = new MeetupEvents($conn);
$events = $e->getEvents(array('key'=>'val'));
```

or, alternatively,

``` php
$conn = OAuth2MeetupConnection({'username': '1234', 'password': '1234'});
$e = new MeetupEvents($conn);
$events = $e->getEvents(array('key'=>'val'));
```

What do you think?

Also, thanks for being so responsive for my pull requests.  This is a great project and I'm excited to know that its developer is on top of it.

Edit:

Giving this a second thought, MeetupConnection should be an interface, and KeyAuthMeetupConnection and OAuth2MeetupConnection should implement that interface.

**Comment by blobaugh** [comment]
That sounds pretty good, except that you will not pass in credentials with oauth. Your structure looks like the basics of what I was looking to do. 

I do not know that I am exactly on top of it as I have not worked on it for months, but I have been wanting to still. Good to have someone else onboard. As you make changes can you also update the wiki? I would like this as documented as possible. Meetup make make it the official client once it support most of the API functionality

**Comment by cjlarose** [comment]
Alright, so we've got OAuth support with the new connection classes:

For key auth:

``` php
$api_key = '12345';
$connection = new MeetupKeyAuthConnection($api_key);
$m = new MeetupEvents($connection);
$events = $m->getEvents( array( 'group_urlname' => '<GROUP URL NAME>' ) );
```

For OAuth:

``` php
$access_token = $_SESSION['meetup_access_token'];
$connection = new MeetupOAuth2Connection($access_token);
$m = new MeetupEvents($connection);
$events = $m->getEvents( array( 'group_urlname' => '<GROUP URL NAME>' ) );
```

For OAuth, you'll notice that the api wrapper is not responsible for the retrieval, verification, renewal, or storage of the access token, and I think this is the most appropriate way to handle it.  Client applications should be responsible for making all of the relevant requests and storing access_tokens in whatever way they prefer (such as sessions like in the example, or in database tables).

Also, I'll update the wiki pages as soon as you pull in the changes.

**Comment by blobaugh** [comment]
I guess that sounds good for the oauth setup. Is it possible to include an example of getting the connection setup in a demo folder or something? Most devs I talk to have no idea how to interact with oauth. It can be tricky so I feel and example would be useful

**Comment by cjlarose** [comment]
Yeah what I can do is post a full working example on the wiki.  And you're right, it can be a pain, so I definitely think dedicating a wiki page to it would help people out.

**Comment by blobaugh** [comment]
Awesome. Thanks for the contributions on this. I love the open source community. I think our discussion around this part feels pretty complete so I will merge it now. After the wiki articles are in, if you are on the mailing list you should announce the new oauth support. If you are not just let me know and I would be happy to do so :)

**Comment by cjlarose** [comment]
Thanks for pulling in the changes.  Be sure to check out the [new wiki page](https://github.com/blobaugh/Meetup-API-client-for-PHP/wiki/OAuth-Integration) if you haven't already.  I'm not on the mailing list, so feel free to make the announcement.  You might want to hold off on that for a little bit, though.  I'm looking at ways to help make OAuth integration a little bit easier with a few helper methods.  I'll pr again if I figure something out.  Thanks again!

**Comment by blobaugh** [comment]
I did not try the code, but that wiki page looks great! Thanks for doing that. Nothing drives me more nuts than grabbing a library and having no documentation with it at all :S. 

I would be delighted to post on the mailing list about this improvement. Poke me whenever you feel it is ready and I will pull the trigger :)

**Pull request merged**
