### PR TITLE
Composer Support

### PR DESCRIPTION
**Pull request by rdohms**
Added support to allow install via Composer (http://getcomposer.org).

This basically means people using it can add "blobaugh/meetup-api-client" to their composer files and it will get the files and generate a autoload file, which will also include the Meetup.php file.

This package still needs to be added to Packagist so that everyone can find it, now they must manually infor the github url.

Adding to packagist can be done easily on this url: http://packagist.org/packages/submit

One more information which may be added to the composer file is the license of the library. Let me know if you like this, i'm gonna start thinking about the namespace structure.

### CODE REVIEW

**Comment by blobaugh** [comment]
This is great. Could you please update the wiki with this info? How to use this project with Composer, etc? Then we can get the new code merged in ASAP. Excellent documentation is one of the core tenets of this project :).

Thanks for your work

**Comment by rdohms** [comment]
Documentation updated.

**Comment by rdohms** [comment]
Don't forget to add it to packagist, or the documentation will need a few more lines :P

**Comment by blobaugh** [comment]
I merged everything you provided :)

**Pull request merged**
